application/urls.py
from django.urls import path

from application.views import views, login, dashboard, subject, category, course, user
from django.conf import settings
from django.conf.urls.static import static
app_name = 'application'

urlpatterns = [
    path('', login.index, name='index'),
    path('login', login.verify_login_without_auth, name='verify_login'),
    path('home', dashboard.index, name='home'),
    path('logout', login.logout, name='logout'),
    path('course', dashboard.index, name='course'),
    path('my_course', course.my_course, name='my_course'),
    path('subject', subject.index, name='subject'),
    path('category', category.index, name='category'),
    path('course_management', course.index, name='course_management'),
    path('user', user.index, name='user'),
    path('report', dashboard.index, name='report'),
    path('lesson/<int:subject_id>', subject.lesson, name='lesson'),
    path('course_student/<int:course_id>', course.course_student, name='course_student'),
    path('lesson_calendar/<int:course_id>', course.lesson_calendar, name='lesson_calendar'),
    path('course_details/<int:course_id>', course.course_details, name='course_details'),
    path('course_add_student', course.course_add_student, name='course_add_student'),
    path('document', course.document, name='document'),
    path('filter_user_lesson/<int:user_id>/<int:lesson_calendar_id>/<int:course_id>', course.filter_user_lesson,
         name='filter_user_lesson'),
    path('list', course.list, name='list')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from tastypie.api import Api
from application.api.resources import UserResource
from application.api.lessoncalendar import LessonCalendarResource
from application.api.lesson import LessonResource
from application.api.category import CategoryResource
from application.api.subject import SubjectResource
from application.api.course import CourseResource
from application.api.userlesson import UserLessonResource
from application.api.user import UserResource

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(SubjectResource())
v1_api.register(CategoryResource())
v1_api.register(CourseResource())
v1_api.register(LessonCalendarResource())
v1_api.register(LessonResource())
v1_api.register(UserLessonResource())
v1_api.register(UserResource())


urlpatterns = [
    #refer other URLconfs by include function
    path('', include('application.urls')),
    url(r'^api/', include(v1_api.urls)),
    path('admin/', admin.site.urls)
]

application/models/course_category.py
from .base import BaseModel
from django.db import models


class CourseCategory(BaseModel):
    course_type = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'course_category'

application/views/category.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
title = 'Web Traning Tool - Subject'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        category_list= CourseCategory.objects.all().order_by("-id").values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'category/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'category_list': category_list,
            'user_list': user_list
        }
        return render(request, 'layout/layout_home.html', data)

application/views/course.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
from application.models.subject import Subject
from application.models.course import Course
from application.models.lesson import Lesson
from application.models.user import User
from application.models.lesson_calendar import LessonCalendar
from application.models.user_lesson import UserLesson
from datetime import datetime
from datetime import datetime as dt
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
import pytz
from django.shortcuts import render

from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.urls import reverse

from application.models.document import Document
from application.form import DocumentForm


title = 'Web Traning Tool - Course'
#https://www.django-rest-framework.org/#quickstart


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        if user['user_roll'] == "1":
            return HttpResponseRedirect(reverse('application:index'))
        if user['user_roll'] == "2":
            course = Course.objects.all().order_by("-id").filter(teacher_id=user['id']).values()
            user_list = User.objects.all().order_by("-id").filter(id=user['id'])
        else:
            course = Course.objects.all().order_by("-id").values()
            user_list = User.objects.all().order_by("-id")
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()


        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course_list': course,
            'category_list': category_list,
            'user_list': user_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def course_student(request, course_id):

    #https://www.youtube.com/watch?v=zhKPDnDQ7-Q
    #UserLesson.objects.filter(lesson_calendar_id__in=[31,32]).values('user_id').annotate(dcount=Count('user_id'))
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar_dict = LessonCalendar.objects.filter(course_id=course_id).values('id')
        lesson_calendar_list = []
        for i in lesson_calendar_dict:
            lesson_calendar_list.append(i['id'])
        # course = Course.objects.all().order_by("-id").values()
        # subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_joined_dict = UserLesson.objects.filter(lesson_calendar_id__in=lesson_calendar_list).values('user_id').\
            annotate(dcount=Count('user_id'))
        user_joined_dict_list = []
        for i in user_joined_dict:
            user_joined_dict_list.append(i['user_id'])
        user_list = User.objects.all().order_by("-id").values()

        for i in range(len(user_list)):
            if user_list[i]['id'] in user_joined_dict_list:
                user_list[i]['join_status'] = True
            else:
                user_list[i]['join_status'] = False
        user = request.session.get('user')
        course = get_object_or_404(Course, pk=course_id)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/course_student.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'user_joined_dict_list': user_joined_dict_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def lesson_calendar(request, course_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar = LessonCalendar.objects.filter(course_id=course_id).values()
        for i in range(len(lesson_calendar)):
            if lesson_calendar[i]['time_start']:
                lesson_calendar[i]['time_start'] = int(lesson_calendar[i]['time_start'])/1000
                d = datetime.fromtimestamp(lesson_calendar[i]['time_start'])
                d = pytz.timezone('Asia/Bangkok').localize(d)
                # d = d.astimezone(pytz.itc)
                lesson_calendar[i]['time_start'] = d.strftime('%m/%d/%Y')
                # ts = int("1284101485")
                # lesson_calendar[i]['time_start'] = datetime.utcfromtimestamp(ts).strftime('%m/%d/%Y')

        course = get_object_or_404(Course, pk=course_id)
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/lesson_calendar.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'lesson_calendar': lesson_calendar
        }
        return render(request, 'layout/layout_home.html', data)


def lesson_calendar(request, course_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar = LessonCalendar.objects.filter(course_id=course_id).values()
        for i in range(len(lesson_calendar)):
            if lesson_calendar[i]['time_start']:
                lesson_calendar[i]['time_start'] = int(lesson_calendar[i]['time_start'])/1000
                d = datetime.fromtimestamp(lesson_calendar[i]['time_start'])
                d = pytz.timezone('Asia/Bangkok').localize(d)
                # d = d.astimezone(pytz.itc)
                lesson_calendar[i]['time_start'] = d.strftime('%m/%d/%Y')
                # ts = int("1284101485")
                # lesson_calendar[i]['time_start'] = datetime.utcfromtimestamp(ts).strftime('%m/%d/%Y')

        course = get_object_or_404(Course, pk=course_id)
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/lesson_calendar.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'lesson_calendar': lesson_calendar
        }
        return render(request, 'layout/layout_home.html', data)


def my_course(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        course = Course.objects.all().order_by("-id").values()
        course_joined = []
        for i in course:
            lesson_calendar_dict = LessonCalendar.objects.filter(course_id=i['id']).values('id')
            lesson_calendar_list = []
            for j in lesson_calendar_dict:
                lesson_calendar_list.append(j['id'])
            u_lesson = UserLesson.objects.filter(user_id=user['id'], lesson_calendar_id__in=lesson_calendar_list)
            if len(u_lesson) > 0:
                course_joined.append(i)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/my_course.html',
            'root_page': 'Home',
            'child_page': 'Dashboard',
            'course_list': course_joined,
            'other': i['id'],
        }
        return render(request, 'layout/layout_home.html', data)


@api_view(['PUT', 'GET', 'DELETE'])
def course_add_student(request):
    """

    :param request:
    user_id: Student join course
    course_id: Course to join
    :param pk:
    :return:
    """
    user_id = request.data['user_id']
    course_id = request.data['course_id']
    lesson_calendar_dict = LessonCalendar.objects.filter(course_id=course_id).values('id')
    lesson_calendar_list = []
    for i in lesson_calendar_dict:
        lesson_calendar_list.append(i['id'])
    user_joined_dict = UserLesson.objects.filter(lesson_calendar_id__in=lesson_calendar_list).values('user_id'). \
        annotate(dcount=Count('user_id'))
    user_joined_dict_list = []
    for i in user_joined_dict:
        user_joined_dict_list.append(i['user_id'])
    if int(user_id) in user_joined_dict_list and request.method == 'PUT':
        return Response('User already create lesson calendar', status=status.HTTP_400_BAD_REQUEST)

    if int(user_id) not in user_joined_dict_list and request.method == 'DELETE':
        return Response('User not in lesson calendar', status=status.HTTP_404_NOT_FOUND)

    for i in lesson_calendar_dict:
        data = {}
        data['lesson_calendar_id'] = i['id']
        data['user_id'] = user_id
        if request.method == 'PUT':
            user_lesson = UserLesson(**data)
            user_lesson.save()
        elif request.method == 'DELETE':

application/views/dashboard.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course import Course
from application.models.user_lesson import UserLesson
from application.models.lesson_calendar import LessonCalendar

title = 'Web Traning Tool - Dashboard'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        course = Course.objects.all().order_by("-id").values()
        course_not_joined = []
        for i in course:
            lesson_calendar_dict = LessonCalendar.objects.filter(course_id=i['id']).values('id')
            lesson_calendar_list = []
            for j in lesson_calendar_dict:
                lesson_calendar_list.append(j['id'])
            u_lesson = UserLesson.objects.filter(user_id=user['id'], lesson_calendar_id__in=lesson_calendar_list)
            if len(u_lesson) == 0:
                course_not_joined.append(i)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'home/dashboard.html',
            'root_page': 'Home',
            'child_page': 'Dashboard',
            'course_list': course_not_joined,
            'other': i['id'],
        }
        return render(request, 'layout/layout_home.html', data)

application/views/subject.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
from application.models.subject import Subject
from application.models.lesson import Lesson
title = 'Web Traning Tool - Subject'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'subject/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'subject_list': subject,
            'category_list': category_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def lesson(request, subject_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        subject = get_object_or_404(Subject, pk=subject_id)
        lesson = Lesson.objects.filter(subject_id=subject_id).values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'lesson/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'subject_object': subject,
            'lesson_list': lesson
        }
        return render(request, 'layout/layout_home.html', data)

application/views/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest


def index(request):
    return render(request, 'login.html')
    #return HttpResponse("Hello, world. You're at the polls index.")

application/templates/course/index.html
{% load static %}
<!-- PAGE CONTENT-->
<div class="page-content--bgf7">
    <!-- BREADCRUMB-->
    <section class="au-breadcrumb2">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    <a href="#">{{ root_page}}</a>
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">{{ child_page}}</li>
                            </ul>
                        </div>
                        <form class="au-form-icon--sm" action="" method="post">
                            <input class="au-input--w300 au-input--style2" type="text" placeholder="Search for datas &amp; reports...">
                            <button class="au-btn--submit2" type="submit">
                                <i class="zmdi zmdi-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END BREADCRUMB-->
    <!-- DATA TABLE-->
    <section class="p-t-20">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title-5 m-b-35">Courses</h3>
                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                            <div class="rs-select2--light rs-select2--md">
                                <select class="js-select2" name="property">
                                    <option selected="selected">All Properties</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <div class="rs-select2--light rs-select2--sm">
                                <select class="js-select2" name="time">
                                    <option selected="selected">Today</option>
                                    <option value="">3 Days</option>
                                    <option value="">1 Week</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <button class="au-btn-filter">
                                <i class="zmdi zmdi-filter-list"></i>filters</button>
                        </div>
                        <div class="table-data__tool-right">
                            <button class="au-btn au-btn-icon au-btn--green au-btn--small" id="btnCreateCourse" data-toggle="modal" data-target="#createCourseModal">
                                <i class="zmdi zmdi-plus"></i>add item</button>
                            <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                                <select class="js-select2" name="type">
                                    <option selected="selected">Export</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive table-responsive-data2">
                        <table class="table table-data2">
                            <thead>
                                <tr>
                                    <th>Course name</th>
                                    <th>Teacher</th>
                                    <th>Start</th>
                                    <th>End</th>
                                    <th>Student</th>
                                    <th>Lesson Calendar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for course in course_list %}
                                    <tr class="tr-shadow">
                                        <td><a href="{% url 'application:course_details' course.id %}">{{ course.course_name }}</a></td>
                                        <td>
                                            <span class="block-email">lori@example.com</span>
                                        </td>
                                        <td>{{ course.start_time }}</td>
                                        <td>{{ course.end_time }}</td>
                                        <td>
                                            <a href="{% url 'application:course_student' course.id %}" class="btn btn-primary btn-sm">Add</a>
                                        </td>
                                        <td >
                                            <a href="{% url 'application:lesson_calendar' course.id %}" class="btn btn-primary btn-sm">Add</a>
                                        </td>
                                        <td>
                                            <div class="table-data-feature">
                                                <button class="item" onclick="callUpdateCourse({{ course.id }})" data-toggle="modal" data-target="#createCourseModal" data-placement="top" title="Edit">
                                                <i class="zmdi zmdi-edit"></i>
                                            </button>
                                                <button class="item" data-toggle="tooltip" onclick="callDeleteCourse({{ course.id }})" data-placement="top" title="Delete">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="spacer"></tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END DATA TABLE-->

    {% include 'partials/copyright.html' %}
</div>
<!-- modal medium add subject -->
<div class="modal fade" id="createCourseModal" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="email-loading" style="display: none;"></div>
            <div class="modal-header">
                <h5 class="modal-title" id="createCourseModalTitle">Create Course</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="create-course">
                <div class="modal-body">
                    <div class="row">
                        <div class="col col-md-12">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Course name</label>
                                <input type="text" id="course_name" placeholder="Enter subject name" class="form-control" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Course type</label>
                                <select name="select" id="course_type_id" class="form-control" onchange="updateSubject(this.value)" required>
                                    <option value="">Please select</option>
                                    {% for category in category_list %}
                                    <option value="{{ category.id }}">{{ category.course_type }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Subject</label>
                                <select name="select" id="subject_id" class="form-control" required>
                                    <option value="">Please select</option>
                                    {% for category in category_list %}
                                    <option value="{{ category.id }}">{{ category.course_type }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Start from</label>
                                <input type="text" class="form-control pull-right" id="datepicker-from" required>
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Start from</label>
                                <input type="text" class="form-control pull-right" id="datepicker-to" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Limit student</label>
                                <input type="number" id="limited" placeholder="Enter number student" class="form-control" required>
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form-group">
                                <label for="company" class=" form-control-label">Teacher</label>
                                <select name="select" id="teacher_id" class="form-control" required>
                                    <option value="">Please select</option>
                                    {% for user in user_list %}
                                    <option value="{{ user.id }}">{{ user.user_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-md-12">
                            <div class="form-group text-dark">
                                <label for="descriptions" class=" form-control-label">Descriptions</label>
                                <textarea cols="80" id="descriptions" name="descriptions" rows="10" >

                                </textarea>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button id="submit-create-course" type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- end modal medium -->