application/urls.py
from django.urls import path

from application.views import views, login, dashboard, subject, category, course, user
from django.conf import settings
from django.conf.urls.static import static
app_name = 'application'

urlpatterns = [
    path('', login.index, name='index'),
    path('login', login.verify_login_without_auth, name='verify_login'),
    path('home', dashboard.index, name='home'),
    path('logout', login.logout, name='logout'),
    path('course', dashboard.index, name='course'),
    path('my_course', course.my_course, name='my_course'),
    path('subject', subject.index, name='subject'),
    path('category', category.index, name='category'),
    path('course_management', course.index, name='course_management'),
    path('user', user.index, name='user'),
    path('report', dashboard.index, name='report'),
    path('lesson/<int:subject_id>', subject.lesson, name='lesson'),
    path('course_student/<int:course_id>', course.course_student, name='course_student'),
    path('lesson_calendar/<int:course_id>', course.lesson_calendar, name='lesson_calendar'),
    path('course_details/<int:course_id>', course.course_details, name='course_details'),
    path('course_add_student', course.course_add_student, name='course_add_student'),
    path('document', course.document, name='document'),
    path('filter_user_lesson/<int:user_id>/<int:lesson_calendar_id>/<int:course_id>', course.filter_user_lesson,
         name='filter_user_lesson'),
    path('list', course.list, name='list')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from tastypie.api import Api
from application.api.resources import UserResource
from application.api.lessoncalendar import LessonCalendarResource
from application.api.lesson import LessonResource
from application.api.category import CategoryResource
from application.api.subject import SubjectResource
from application.api.course import CourseResource
from application.api.userlesson import UserLessonResource
from application.api.user import UserResource

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(SubjectResource())
v1_api.register(CategoryResource())
v1_api.register(CourseResource())
v1_api.register(LessonCalendarResource())
v1_api.register(LessonResource())
v1_api.register(UserLessonResource())
v1_api.register(UserResource())


urlpatterns = [
    #refer other URLconfs by include function
    path('', include('application.urls')),
    url(r'^api/', include(v1_api.urls)),
    path('admin/', admin.site.urls)
]

application/models/course_category.py
from .base import BaseModel
from django.db import models


class CourseCategory(BaseModel):
    course_type = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'course_category'

application/views/category.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
title = 'Web Traning Tool - Subject'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        category_list= CourseCategory.objects.all().order_by("-id").values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'category/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'category_list': category_list,
            'user_list': user_list
        }
        return render(request, 'layout/layout_home.html', data)

application/views/course.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
from application.models.subject import Subject
from application.models.course import Course
from application.models.lesson import Lesson
from application.models.user import User
from application.models.lesson_calendar import LessonCalendar
from application.models.user_lesson import UserLesson
from datetime import datetime
from datetime import datetime as dt
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
import pytz
from django.shortcuts import render

from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.urls import reverse

from application.models.document import Document
from application.form import DocumentForm


title = 'Web Traning Tool - Course'
#https://www.django-rest-framework.org/#quickstart


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        if user['user_roll'] == "1":
            return HttpResponseRedirect(reverse('application:index'))
        if user['user_roll'] == "2":
            course = Course.objects.all().order_by("-id").filter(teacher_id=user['id']).values()
            user_list = User.objects.all().order_by("-id").filter(id=user['id'])
        else:
            course = Course.objects.all().order_by("-id").values()
            user_list = User.objects.all().order_by("-id")
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()


        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course_list': course,
            'category_list': category_list,
            'user_list': user_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def course_student(request, course_id):

    #https://www.youtube.com/watch?v=zhKPDnDQ7-Q
    #UserLesson.objects.filter(lesson_calendar_id__in=[31,32]).values('user_id').annotate(dcount=Count('user_id'))
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar_dict = LessonCalendar.objects.filter(course_id=course_id).values('id')
        lesson_calendar_list = []
        for i in lesson_calendar_dict:
            lesson_calendar_list.append(i['id'])
        # course = Course.objects.all().order_by("-id").values()
        # subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_joined_dict = UserLesson.objects.filter(lesson_calendar_id__in=lesson_calendar_list).values('user_id').\
            annotate(dcount=Count('user_id'))
        user_joined_dict_list = []
        for i in user_joined_dict:
            user_joined_dict_list.append(i['user_id'])
        user_list = User.objects.all().order_by("-id").values()

        for i in range(len(user_list)):
            if user_list[i]['id'] in user_joined_dict_list:
                user_list[i]['join_status'] = True
            else:
                user_list[i]['join_status'] = False
        user = request.session.get('user')
        course = get_object_or_404(Course, pk=course_id)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/course_student.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'user_joined_dict_list': user_joined_dict_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def lesson_calendar(request, course_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar = LessonCalendar.objects.filter(course_id=course_id).values()
        for i in range(len(lesson_calendar)):
            if lesson_calendar[i]['time_start']:
                lesson_calendar[i]['time_start'] = int(lesson_calendar[i]['time_start'])/1000
                d = datetime.fromtimestamp(lesson_calendar[i]['time_start'])
                d = pytz.timezone('Asia/Bangkok').localize(d)
                # d = d.astimezone(pytz.itc)
                lesson_calendar[i]['time_start'] = d.strftime('%m/%d/%Y')
                # ts = int("1284101485")
                # lesson_calendar[i]['time_start'] = datetime.utcfromtimestamp(ts).strftime('%m/%d/%Y')

        course = get_object_or_404(Course, pk=course_id)
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/lesson_calendar.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'lesson_calendar': lesson_calendar
        }
        return render(request, 'layout/layout_home.html', data)


def lesson_calendar(request, course_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        lesson_calendar = LessonCalendar.objects.filter(course_id=course_id).values()
        for i in range(len(lesson_calendar)):
            if lesson_calendar[i]['time_start']:
                lesson_calendar[i]['time_start'] = int(lesson_calendar[i]['time_start'])/1000
                d = datetime.fromtimestamp(lesson_calendar[i]['time_start'])
                d = pytz.timezone('Asia/Bangkok').localize(d)
                # d = d.astimezone(pytz.itc)
                lesson_calendar[i]['time_start'] = d.strftime('%m/%d/%Y')
                # ts = int("1284101485")
                # lesson_calendar[i]['time_start'] = datetime.utcfromtimestamp(ts).strftime('%m/%d/%Y')

        course = get_object_or_404(Course, pk=course_id)
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user_list = User.objects.all().order_by("-id").values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/lesson_calendar.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'course': course,
            'category_list': category_list,
            'user_list': user_list,
            'lesson_calendar': lesson_calendar
        }
        return render(request, 'layout/layout_home.html', data)


def my_course(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        course = Course.objects.all().order_by("-id").values()
        course_joined = []
        for i in course:
            lesson_calendar_dict = LessonCalendar.objects.filter(course_id=i['id']).values('id')
            lesson_calendar_list = []
            for j in lesson_calendar_dict:
                lesson_calendar_list.append(j['id'])
            u_lesson = UserLesson.objects.filter(user_id=user['id'], lesson_calendar_id__in=lesson_calendar_list)
            if len(u_lesson) > 0:
                course_joined.append(i)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'course/my_course.html',
            'root_page': 'Home',
            'child_page': 'Dashboard',
            'course_list': course_joined,
            'other': i['id'],
        }
        return render(request, 'layout/layout_home.html', data)


@api_view(['PUT', 'GET', 'DELETE'])
def course_add_student(request):
    """

    :param request:
    user_id: Student join course
    course_id: Course to join
    :param pk:
    :return:
    """
    user_id = request.data['user_id']
    course_id = request.data['course_id']
    lesson_calendar_dict = LessonCalendar.objects.filter(course_id=course_id).values('id')
    lesson_calendar_list = []
    for i in lesson_calendar_dict:
        lesson_calendar_list.append(i['id'])
    user_joined_dict = UserLesson.objects.filter(lesson_calendar_id__in=lesson_calendar_list).values('user_id'). \
        annotate(dcount=Count('user_id'))
    user_joined_dict_list = []
    for i in user_joined_dict:
        user_joined_dict_list.append(i['user_id'])
    if int(user_id) in user_joined_dict_list and request.method == 'PUT':
        return Response('User already create lesson calendar', status=status.HTTP_400_BAD_REQUEST)

    if int(user_id) not in user_joined_dict_list and request.method == 'DELETE':
        return Response('User not in lesson calendar', status=status.HTTP_404_NOT_FOUND)

    for i in lesson_calendar_dict:
        data = {}
        data['lesson_calendar_id'] = i['id']
        data['user_id'] = user_id
        if request.method == 'PUT':
            user_lesson = UserLesson(**data)
            user_lesson.save()
        elif request.method == 'DELETE':

application/views/dashboard.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course import Course
from application.models.user_lesson import UserLesson
from application.models.lesson_calendar import LessonCalendar

title = 'Web Traning Tool - Dashboard'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        user = request.session.get('user')
        course = Course.objects.all().order_by("-id").values()
        course_not_joined = []
        for i in course:
            lesson_calendar_dict = LessonCalendar.objects.filter(course_id=i['id']).values('id')
            lesson_calendar_list = []
            for j in lesson_calendar_dict:
                lesson_calendar_list.append(j['id'])
            u_lesson = UserLesson.objects.filter(user_id=user['id'], lesson_calendar_id__in=lesson_calendar_list)
            if len(u_lesson) == 0:
                course_not_joined.append(i)
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'home/dashboard.html',
            'root_page': 'Home',
            'child_page': 'Dashboard',
            'course_list': course_not_joined,
            'other': i['id'],
        }
        return render(request, 'layout/layout_home.html', data)

application/views/subject.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView
from application.models.user import User
from django.contrib.auth.decorators import login_required
from application.models.course_category import CourseCategory
from application.models.subject import Subject
from application.models.lesson import Lesson
title = 'Web Traning Tool - Subject'


@login_required(login_url='')
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        subject = Subject.objects.all().order_by("-id").values()
        category_list = CourseCategory.objects.all().values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'subject/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'subject_list': subject,
            'category_list': category_list
        }
        return render(request, 'layout/layout_home.html', data)


@login_required(login_url='')
def lesson(request, subject_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('application:index'))
    else:
        subject = get_object_or_404(Subject, pk=subject_id)
        lesson = Lesson.objects.filter(subject_id=subject_id).values()
        user = request.session.get('user')
        data = {
            'title': title,
            'user_data': user,
            'temp_template': 'lesson/index.html',
            'root_page': 'Course',
            'child_page': 'Subject',
            'subject_object': subject,
            'lesson_list': lesson
        }
        return render(request, 'layout/layout_home.html', data)

application/views/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest


def index(request):
    return render(request, 'login.html')
    #return HttpResponse("Hello, world. You're at the polls index.")

application/templates/partials/copyright.html
<!-- COPYRIGHT-->
<section class="p-t-60 p-b-20">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2019 Terralogic Inc. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END COPYRIGHT-->

<!-- CONFIRM MODAL -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="staticModalLabel" aria-hidden="true"
 data-backdrop="static">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalTitle">Static Modal</h5>
                <button type="button" class="close confirm-close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="confirmModalBody">
                    This is a static modal, backdrop click will not close it.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary confirm-close" data-dismiss="modal">Cancel</button>
                <button id="confirmModalConfirm" type="button" class="btn btn-primary">Confirm</button>
            </div>
        </div>
    </div>
</div>
<!-- END CONFIRM MODAL -->
<!-- RESULT MODAL -->
<div class="modal fade" id="resultModal" tabindex="-1" role="dialog" aria-labelledby="staticModalLabel" aria-hidden="true"
 data-backdrop="static">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultModalTitle">Static Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="resultModalBody">
                    This is a static modal, backdrop click will not close it.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary " data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<!-- END RESULT MODAL -->

application/templates/partials/importjs.html
{% load static %}

<!-- Bootstrap JS-->
<script src="{% static 'vendor/bootstrap-4.1/popper.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js'%}"></script>
<!-- Vendor JS       -->
<script src="{% static 'vendor/slick/slick.min.js'%}">
</script>
<script src="{% static 'vendor/wow/wow.min.js'%}"></script>
<script src="{% static 'vendor/animsition/animsition.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js'%}">
</script>
<script src="{% static 'vendor/counter-up/jquery.waypoints.min.js'%}"></script>
<script src="{% static 'vendor/counter-up/jquery.counterup.min.js'%}">
</script>
<script src="{% static 'vendor/circle-progress/circle-progress.min.js'%}"></script>
<script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js'%}"></script>
<script src="{% static 'vendor/chartjs/Chart.bundle.min.js'%}"></script>
<script src="{% static 'vendor/select2/select2.min.js'%}"></script>

<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'vendor/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'%}"></script>



<!-- bootstrap datepicker -->
<script src="{% static 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'%}"></script>

<!-- Main JS-->
<script src="{% static 'js/main.js'%}?v=7"></script>

<!-- My scripts -->
<script src="{% static 'js/my_scripts.js'%}?v=87"></script>

application/templates/partials/menu.html
{% load static %}
<!-- HEADER DESKTOP-->
<header class="header-desktop3 d-none d-lg-block">
	<div class="section__content section__content--p35">
		<div class="header3-wrap">
			<div class="header__logo">
				<a href="#">
					<img src="{% static 'images/logo.png' %}" alt="Web Tranining Tool" />
				</a>
			</div>
			<div class="header__navbar">
				<ul class="list-unstyled">
					<li class="has-sub">
						<a href="{% url 'application:home' %}">
							<i class="fas fa-tachometer-alt"></i>Dashboard
							<span class="bot-line"></span>
						</a>
					</li>
					<li class="has-sub">
						<a href="{% url 'application:my_course' %}">
							<i class="fas fa-graduation-cap"></i>My Course
							<span class="bot-line"></span>
						</a>
					</li>
					{% if user_data.user_roll == "2" or user_data.user_roll == "3" %}
						<li class="has-sub">
							<a href="#">
								<i class="fas fa-folder-open"></i>
								<span class="bot-line"></span>Course</a>
							<ul class="header3-sub-list list-unstyled">
								<li>
									<a href="{% url 'application:subject' %}">Subject</a>
								</li>
								<li>
									<a href="{% url 'application:category' %}">Course Category</a>
								</li>
								<li>
									<a href="{% url 'application:course_management' %}">Course Management</a>
								</li>
							</ul>
						</li>
					{% endif %}
					{% if user_data.user_roll == "3" %}
					<li class="has-sub">
						<a href="#">
							<i class="fas fa-users"></i>
							<span class="bot-line"></span>User</a>
							<ul class="header3-sub-list list-unstyled">
								<li>
									<a href="{% url 'application:user' %}">User list</a>
								</li>
								<li>
									<a href="{% url 'application:user' %}">User Permisson</a>
								</li>
							</ul>
					</li>
					{% endif %}
					{% if user_data.user_roll == "3" %}
					<li>
						<a href="{% url 'application:report' %}">
							<i class="fa fa-line-chart"></i>
							<span class="bot-line"></span>Report</a>
					</li>
					{% endif %}
				</ul>
			</div>
			<div class="header__tool">
				<div class="header-button-item has-noti js-item-menu">
					<i class="zmdi zmdi-notifications"></i>
					<div class="notifi-dropdown notifi-dropdown--no-bor js-dropdown">
						<div class="notifi__title">
							<p>You have 3 Notifications</p>
						</div>
						<div class="notifi__item">
							<div class="bg-c1 img-cir img-40">
								<i class="zmdi zmdi-email-open"></i>
							</div>
							<div class="content">
								<p>You got a email notification</p>
								<span class="date">April 12, 2018 06:50</span>
							</div>
						</div>
						<div class="notifi__item">
							<div class="bg-c2 img-cir img-40">
								<i class="zmdi zmdi-account-box"></i>
							</div>
							<div class="content">
								<p>Your account has been blocked</p>
								<span class="date">April 12, 2018 06:50</span>
							</div>
						</div>
						<div class="notifi__item">
							<div class="bg-c3 img-cir img-40">
								<i class="zmdi zmdi-file-text"></i>
							</div>
							<div class="content">
								<p>You got a new file</p>
								<span class="date">April 12, 2018 06:50</span>
							</div>
						</div>
						<div class="notifi__footer">
							<a href="#">All notifications</a>
						</div>
					</div>
				</div>
				<div class="account-wrap">
					<div class="account-item account-item--style2 clearfix js-item-menu">
						<div class="image">
							<img src="{% static 'images/default_avatar.png' %}" alt="John Doe" />
						</div>
						<div class="content">
							<a class="js-acc-btn" href="#">{{ user_data.fullName }}</a>
						</div>
						<div class="account-dropdown js-dropdown">
							<div class="info clearfix">
								<div class="image">
									<a href="#">
										<img src="{% static 'images/default_avatar.png' %}" alt="John Doe" />
									</a>
								</div>
								<div class="content">
									<h5 class="name">
										<a href="#">{{ user_data.fullName }}</a>
									</h5>
									<span class="email">{{ user_data.email }}</span>
								</div>
							</div>
							<div class="account-dropdown__body">
								<div class="account-dropdown__item">
									<a href="#">
										<i class="zmdi zmdi-account"></i>Account</a>
								</div>
								<div class="account-dropdown__item">
									<a href="#">
										<i class="zmdi zmdi-settings"></i>Setting</a>
								</div>
								<div class="account-dropdown__item">
									<a href="#">
										<i class="zmdi zmdi-notifications"></i>Notifications</a>
								</div>
							</div>
							<div class="account-dropdown__footer">
								<a href="{% url 'application:logout' %}">
									<i class="zmdi zmdi-power"></i>Logout</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!-- END HEADER DESKTOP-->

<!-- HEADER MOBILE-->
<header class="header-mobile header-mobile-2 d-block d-lg-none">
	<div class="header-mobile__bar">
		<div class="container-fluid">
			<div class="header-mobile-inner">
				<a class="logo" href="index.html">
					<img src="static/images/logo.png" alt="Web Tranining Tool" />
				</a>
				<button class="hamburger hamburger--slider" type="button">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</button>
			</div>
		</div>
	</div>
	<nav class="navbar-mobile">
		<div class="container-fluid">
			<ul class="navbar-mobile__list list-unstyled">
				<li>
					<a href="{% url 'application:home' %}">
						<i class="fas fa-tachometer-alt"></i>Dashboard</a>
				</li>
				<li >
					<a href="{% url 'application:my_course' %}">
						<i class="fas fa-graduation-cap"></i>My Course</a>
				</li>
				{% if user_data.user_roll == "2" or user_data.user_roll == "3" %}
					<li class="has-sub">
						<a class="js-arrow" href="#">
							<i class="fas fa-folder-open"></i>Course</a>
						<ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
							<li>
								<a href="{% url 'application:subject' %}">Subject</a>
							</li>
							<li>
								<a href="{% url 'application:category' %}">Course Category</a>
							</li>
							<li>
								<a href="{% url 'application:course_management' %}">Course Management</a>
							</li>
						</ul>
					</li>
				{% endif %}
				{% if user_data.user_roll == "3" %}
					<li class="has-sub">
						<a class="js-arrow" href="#">
							<i class="fas fa-users"></i>User</a>
						<ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
							<li>
								<a href="{% url 'application:user' %}">User List</a>
							</li>
							<li>
								<a href="{% url 'application:user' %}">User Permisson</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="{% url 'application:report' %}">
							<i class="fa fa-line-chart"></i>Report</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</nav>
</header>
<div class="sub-header-mobile-2 d-block d-lg-none">
	<div class="header__tool">
		<div class="header-button-item has-noti js-item-menu">
			<i class="zmdi zmdi-notifications"></i>
			<div class="notifi-dropdown notifi-dropdown--no-bor js-dropdown">
				<div class="notifi__title">
					<p>You have 3 Notifications</p>
				</div>
				<div class="notifi__item">
					<div class="bg-c1 img-cir img-40">
						<i class="zmdi zmdi-email-open"></i>
					</div>
					<div class="content">
						<p>You got a email notification</p>
						<span class="date">April 12, 2018 06:50</span>
					</div>
				</div>
				<div class="notifi__item">
					<div class="bg-c2 img-cir img-40">
						<i class="zmdi zmdi-account-box"></i>
					</div>
					<div class="content">
						<p>Your account has been blocked</p>
						<span class="date">April 12, 2018 06:50</span>
					</div>
				</div>
				<div class="notifi__item">
					<div class="bg-c3 img-cir img-40">
						<i class="zmdi zmdi-file-text"></i>
					</div>
					<div class="content">
						<p>You got a new file</p>
						<span class="date">April 12, 2018 06:50</span>
					</div>
				</div>
				<div class="notifi__footer">
					<a href="#">All notifications</a>
				</div>
			</div>
		</div>
		<div class="account-wrap">
			<div class="account-item account-item--style2 clearfix js-item-menu">
				<div class="image">
					<img src="{% static 'images/default_avatar.png' %}" alt="{{ user_data.fullName }}" />
				</div>
				<div class="content">
					<a class="js-acc-btn" href="#">{{ user_data.fullName }}</a>
				</div>
				<div class="account-dropdown js-dropdown">
					<div class="info clearfix">
						<div class="image">
							<a href="#">
								<img src="{% static 'images/default_avatar.png' %}" alt="{{ user_data.fullName }}" />
							</a>
						</div>
						<div class="content">
							<h5 class="name">
								<a href="#">{{ user_data.fullName }}</a>
							</h5>
							<span class="email">{{ user_data.email }}</span>
						</div>
					</div>
					<div class="account-dropdown__body">
						<div class="account-dropdown__item">
							<a href="#">
								<i class="zmdi zmdi-account"></i>Account</a>
						</div>
						<div class="account-dropdown__item">
							<a href="#">
								<i class="zmdi zmdi-settings"></i>Setting</a>
						</div>
						<div class="account-dropdown__item">
							<a href="#">
								<i class="zmdi zmdi-notifications"></i>Notifications</a>
						</div>
					</div>
					<div class="account-dropdown__footer">
						<a href="{% url 'application:logout' %}">
							<i class="zmdi zmdi-power"></i>Logout</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END HEADER MOBILE -->